### ISSUE TITLE
The Output property is not set for project (Forms)

### ISSUE THREAD

**Issue by Jhanbury** [PrismLibrary/Prism-Extensibility#21] opened 2017-11-13 23:36 UTC
Error occurs when creating a new Prism Xamarin Forms Project with the new Template.

## Info:

- Platform: Android
- Prism version: 7.0.0.168-pre
- Xamarin Forms version: 2.4.0.74863
- No UWP project selected
- Visual Studio version:  15.4.3

## How to reproduce

1. Install Prism Template Pack
2. Create new Project
3. Select DryIoc as DI Container
4. Select Android and iOS only
5. Project generates
6. Select Android project as startup Project
7. Restore Packages and build
8. Error appears

## Error 

The OutputPath property is not set for project 'YourAppName.Android.csproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='AnyCPU'.  This error may also appear if some other project is trying to follow a project-to-project reference to this project, this project has been unloaded or is not included in the solution, and the referencing project does not build using the same or an equivalent Configuration or Platform.	

Let me know if you need anything to help recreate the issue.

Thanks for all the work you guys have put in.
 Love the library really looking forward to using Prism 7

**Comment by brianlagunas** [comment] 2017-11-13 23:43
Hmmm... Interesting. Thanks for reporting this.  Let me look into it.

**Comment by brianlagunas** [comment] 2017-11-13 23:46
What version of the template pack are you using?

**Comment by Jhanbury** [comment] 2017-11-13 23:47
2.0.6

**Comment by brianlagunas** [comment] 2017-11-13 23:48
I am unable to reproduce this error.  if you open up your properties for your Android project and look at the output path, what does it say?

**Comment by Jhanbury** [comment] 2017-11-13 23:50
bin\Debug\

**Comment by brianlagunas** [comment] 2017-11-13 23:50
So it is set!  Just try changing it. Delete the "\" and then re-add it and recompile.

**Comment by Jhanbury** [comment] 2017-11-13 23:53
That's done the trick! I assume that's a miss config on my part.
Thanks for the help @brianlagunas  really appreciate it and again love the Library.

**Comment by brianlagunas** [comment] 2017-11-13 23:54
No prob.  VS 15.4.2+ has a number of little issues.  I am really hoping that these are fixed in the upcoming 15.5 release.

**Closed** 2017-11-13 23:53 UTC
